# Todoodle 코드 품질 규칙
# Effective Dart + Flutter Best Practices
#
# 참고: https://dart.dev/effective-dart

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    dead_code: warning
    unused_import: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

linter:
  rules:
    # ═══════════════════════════════════════════════════════════════
    # Effective Dart: 스타일
    # ═══════════════════════════════════════════════════════════════
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: true
    sort_constructors_first: true

    # ═══════════════════════════════════════════════════════════════
    # Effective Dart: 불변성 & const
    # ═══════════════════════════════════════════════════════════════
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true

    # ═══════════════════════════════════════════════════════════════
    # 코드 품질
    # ═══════════════════════════════════════════════════════════════
    avoid_print: true
    avoid_unnecessary_containers: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    use_super_parameters: true

    # ═══════════════════════════════════════════════════════════════
    # Flutter 위젯 최적화
    # ═══════════════════════════════════════════════════════════════
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true

    # ═══════════════════════════════════════════════════════════════
    # 비활성화 (프로젝트 특성)
    # ═══════════════════════════════════════════════════════════════
    lines_longer_than_80_chars: false
    always_specify_types: false
